### ISSUE TITLE
imgur uploads not working

### ISSUE THREAD

**Issue by Lion115e** [phin05/discord-rich-presence-plex#103]
imgur uploads were working fine up until recently, but i just noticed that discord now just displays a placeholder icon and the program is showing this every time. tried making a new imgur application and putting in the new client ID but same result. not sure if this is an error on the program or on imgur's end so any info would be appreciated :)
![image](https://github.com/user-attachments/assets/2d02c896-7a94-4b2f-b790-b2208904213a)

**Comment by phin05** [comment]
Imgur uploads are working fine for me as well.

@Lion115e Can you check the console output using [v2.11.0](https://github.com/phin05/discord-rich-presence-plex/releases/tag/v2.11.0)? I've added some debug logging for the Imgur upload request.

**Comment by Lion115e** [comment]
hi @phin05 i get this now

[03-11-2024 06:32:44 PM] [DEBUG] [SERVER_NAME] Uploading image to Imgur
[03-11-2024 06:32:44 PM] [DEBUG] HTTP 503, {'Connection': 'close', 'Content-Length': '442', 'Retry-After': '0', 'Content-Type': 'text/html; charset=utf-8', 'Accept-Ranges': 'bytes', 'Date': 'Sun, 03 Nov 2024 18:32:44 GMT', 'X-Served-By': 'cache-lon420130-LON', 'X-Cache': 'MISS', 'X-Cache-Hits': '0', 'X-Timer': 'S1730658764.444678,VS0,VE334', 'access-control-allow-methods': 'GET, PUT, POST, PATCH, DELETE, OPTIONS', 'Server': 'cat factory 1.0', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Credentials': 'true', 'X-Frame-Options': 'DENY', 'Access-Control-Allow-Headers': 'Authorization, Content-Type, Accept, X-Mashape-Authorization, IMGURPLATFORM, IMGURUIDJAFO, sessionCount, IMGURMWBETA, IMGURMWBETAOPTIN, X-expSNKPK127, X-Imgur-Defender-Bypass'}, <?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
  <head>
    <title>503 client read error</title>
  </head>
  <body>
    <h1>Error 503 client read error</h1>
    <p>client read error</p>
    <h3>Error 54113</h3>
    <p>Details: cache-lon420130-LON 1730658765 259973383</p>
    <hr>
    <p>Varnish cache server</p>
  </body>
</html>
[03-11-2024 06:32:44 PM] [ERROR] An unexpected error occured while uploading an image to Imgur
Traceback (most recent call last):
  File "C:\Users\USER_NAME\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER_NAME\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER_NAME\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER_NAME\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Programs\discord-rich-presence-plex-v2.11.0\discord-rich-presence-plex\core\imgur.py", line 26, in uploadToImgur
    data: models.imgur.UploadResponse = response.json()
                                        ^^^^^^^^^^^^^^^
  File "C:\Users\USER_NAME\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 2 column 1 (char 1)

**Comment by phin05** [comment]
```

**Comment by phin05** [comment]
Support for [Litterbox](https://litterbox.catbox.moe/) as an alternative image uploader has been added in [v2.14.0](https://github.com/phin05/discord-rich-presence-plex/releases/tag/v2.14.0). It will be used if `display.posters.enabled` is set to `true` and `display.posters.imgurClientID` is empty. No credentials are required.
