### ISSUE TITLE
Unable To Start Application

### ISSUE THREAD

**Issue by zluckytraveler** [phin05/discord-rich-presence-plex#58]
I'm unable to start the application, and this is the output error I receive. I all requirements have been installed, and I have python 3.11.0 installed as well.

I am using an Apple Mac Mini M1 on macOS Monterey v12.6

```
Traceback (most recent call last):
  File "/Applications/Apps/Programs/Discord/Plex-RPC 3.0/bot.py", line 1, in <module>
    from services import PlexAlertListener
  File "/Applications/Apps/Programs/Discord/Plex-RPC 3.0/services/__init__.py", line 2, in <module>
    from .PlexAlertListener import PlexAlertListener as PlexAlertListener
  File "/Applications/Apps/Programs/Discord/Plex-RPC 3.0/services/PlexAlertListener.py", line 13, in <module>
    from utils.text import formatSeconds
  File "/Applications/Apps/Programs/Discord/Plex-RPC 3.0/utils/text.py", line 3, in <module>
    def formatSeconds(seconds: int | float, joiner: Optional[str] = None) -> str:
TypeError: unsupported operand type(s) for |: 'type' and 'type'
```

**Comment by phin05** [comment]
That looks like the script is being executed by a Python version older than 3.10 even though you have 3.11 installed.

Use `--version` with the Python command you're using (e.g. `python --version`) to check which version is being used.

**Comment by zluckytraveler** [comment]
So it looks like for some reason it was using an old version of python, however I got that fixed and for it to be using the newest version. However now I am getting a different error for the requests module, and I have all requirements installed.

```
Lucky@p8-6 Plex-RPC 3.0 % pip install -r requirements.txt          
Collecting PlexAPI==4.10.1
  Using cached PlexAPI-4.10.1-py3-none-any.whl (141 kB)
Collecting requests==2.26.0
  Using cached requests-2.26.0-py2.py3-none-any.whl (62 kB)
Collecting websocket-client==1.3.2
  Using cached websocket_client-1.3.2-py3-none-any.whl (54 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting charset-normalizer~=2.0.0
  Using cached charset_normalizer-2.0.12-py3-none-any.whl (39 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2022.9.24-py3-none-any.whl (161 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.12-py2.py3-none-any.whl (140 kB)
Installing collected packages: websocket-client, urllib3, idna, charset-normalizer, certifi, requests, PlexAPI
Successfully installed PlexAPI-4.10.1 certifi-2022.9.24 charset-normalizer-2.0.12 idna-3.4 requests-2.26.0 urllib3-1.26.12 websocket-client-1.3.2
Lucky@p8-6 Plex-RPC 3.0 % python3 bot.py
Traceback (most recent call last):
  File "/Applications/Apps/Programs/Discord/Plex-RPC 3.0/bot.py", line 1, in <module>
    from services import PlexAlertListener
  File "/Applications/Apps/Programs/Discord/Plex-RPC 3.0/services/__init__.py", line 2, in <module>
    from .PlexAlertListener import PlexAlertListener as PlexAlertListener
  File "/Applications/Apps/Programs/Discord/Plex-RPC 3.0/services/PlexAlertListener.py", line 6, in <module>
    from .imgur import uploadImage
  File "/Applications/Apps/Programs/Discord/Plex-RPC 3.0/services/imgur.py", line 5, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

**Comment by phin05** [comment]
Try `python3 -m pip install -r requirements.txt` instead.

**Comment by zluckytraveler** [comment]
That's exactly what I did first. I just ran this command just now so you could see it was installed. I however did get it work, for some reason it wouldn't registered that they were installed when using the requirements.txt file, so I just tried installing them one by one with `pip` and it worked, kinda odd.
