### ISSUE TITLE
Rich presence doesn't work with Linux

### ISSUE THREAD

**Issue by Matth3wW** [phin05/discord-rich-presence-plex#60]
Posting this for anyone else that encounters this problem. I installed and successfully set up the script on Kubuntu 22.10 with python 3.10.7 and ensured Discord rich presence was enabled.

**If you have discord installed as a snap, rich presence will not work with most programs. This is not a problem with the script, it is a problem with snap. Uninstall discord as a snap `snap remove discord` and reinstall it as a deb or the equivalent for your distro.**

Below is the error I received.

[28-11-2022 12:36:00 PM] [INFO] Discord Rich Presence for Plex - v2.3.2

[28-11-2022 12:36:00 PM] [INFO] [WoodwardMC/35B9D] Signing into Plex

[28-11-2022 12:36:01 PM] [INFO] [WoodwardMC/35B9D] Signed in as Plex user "MatthewWoodward"

[28-11-2022 12:36:02 PM] [INFO] [WoodwardMC/35B9D] Connecting to Plex Media Server "WoodwardMC"

[28-11-2022 12:36:32 PM] [INFO] [WoodwardMC/35B9D] Connected to Plex Media Server "WoodwardMC"

[28-11-2022 12:36:32 PM] [INFO] [WoodwardMC/35B9D] Listening for alerts from user "MatthewWoodward"

[28-11-2022 12:36:40 PM] [DEBUG] [WoodwardMC/35B9D] Received alert: {'sessionKey': '36', 'clientIdentifier': 'X', 'guid': '', 'ratingKey': '103937', 'url': '', 'key': '/library/metadata/103937', 'viewOffset': 1135000, 'playQueueItemID': 322078, 'playQueueID': 5980, 'state': 'playing', 'transcodeSession': 'X'}

[28-11-2022 12:36:40 PM] [DEBUG] [WoodwardMC/35B9D] Searching sessions for session key 36

[28-11-2022 12:36:40 PM] [DEBUG] [WoodwardMC/35B9D] <Track:131071:Lithium>, Session Key: 38, Usernames: ['MatthewWoodward']

[28-11-2022 12:36:40 PM] [DEBUG] [WoodwardMC/35B9D] <Episode:103937:Ghost-Adventures-s16e07>, Session Key: 36, Usernames: ['Zac Woodward']

[28-11-2022 12:36:40 PM] [DEBUG] [WoodwardMC/35B9D] Session found

[28-11-2022 12:36:40 PM] [DEBUG] [WoodwardMC/35B9D] Username "Zac Woodward" doesn't match "MatthewWoodward", ignoring

[28-11-2022 12:36:41 PM] [DEBUG] [WoodwardMC/35B9D] Received alert: {'sessionKey': '38', 'clientIdentifier': 'X', 'guid': '', 'ratingKey': '131071', 'url': '', 'key': '/library/metadata/131071', 'viewOffset': 184893, 'playQueueItemID': 323665, 'playQueueID': 6043, 'state': 'playing'}

[28-11-2022 12:36:41 PM] [DEBUG] [WoodwardMC/35B9D] Searching sessions for session key 38

[28-11-2022 12:36:41 PM] [DEBUG] [WoodwardMC/35B9D] <Track:131071:Lithium>, Session Key: 38, Usernames: ['MatthewWoodward']

[28-11-2022 12:36:41 PM] [DEBUG] [WoodwardMC/35B9D] Session found

[28-11-2022 12:36:41 PM] [DEBUG] [WoodwardMC/35B9D] Username "MatthewWoodward" matches "MatthewWoodward", continuing

[28-11-2022 12:36:41 PM] [INFO] Connecting Discord IPC Pipe

[28-11-2022 12:36:41 PM] [ERROR] An unexpected error occured during a RPC handshake operation
Traceback (most recent call last):

  File "/home/matthew/Downloads/discord-rich-presence-plex-master/services/DiscordRpcService.py", line 34, in handshake
    self.pipeReader, self.pipeWriter = await asyncio.open_unix_connection(self.ipcPipe) # type: ignore

  File "/usr/lib/python3.10/asyncio/streams.py", line 97, in open_unix_connection
    transport, _ = await loop.create_unix_connection(

  File "/usr/lib/python3.10/asyncio/unix_events.py", line 254, in create_unix_connection
    await self.sock_connect(sock, path)

  File "/usr/lib/python3.10/asyncio/selector_events.py", line 500, in sock_connect
    return await fut

  File "/usr/lib/python3.10/asyncio/selector_events.py", line 505, in _sock_connect
    sock.connect(address)

FileNotFoundError: [Errno 2] No such file or directory

**Comment by arlenreyb** [comment]
I'm getting this exact same error on a Ubuntu server installation with no UI.
Will this script simply not work unless you have a UI?

I followed the instructions to install discord without using snap, found here: https://linuxhint.com/install-discord-ubuntu22-04/
Both method 3 (deb) and method 4 (flatpak) don't make any difference, the error message in the script is the same.

Am I missing something?
