### ISSUE TITLE
An unexpected error occured while closing an IPC pipe reader

### ISSUE THREAD

**Issue by N72826** [phin05/discord-rich-presence-plex#64]
This is by far the best plex rich presence project for discord both in terms of functionality and aesthetics, so thank you for spending time on this. I am getting this error and am not sure if it's a problem on my end or if it is reproducible. If it is a problem on my end (related to faulty dependency installations or something) how would I go about fixing it?

```
[20-03-2023 09:14:13 AM] [DEBUG] [Server Name/1364C] Request for list of clients to check connection: []
[20-03-2023 09:14:18 AM] [DEBUG] [Server Name/1364C] No recent updates from session key 3
[20-03-2023 09:14:18 AM] [INFO] Disconnecting Discord IPC Pipe
[20-03-2023 09:14:18 AM] [ERROR] An unexpected error occured while closing an IPC pipe reader
Traceback (most recent call last):
  File "C:\tools\discord-rich-presence-plex\services\DiscordRpcService.py", line 73, in disconnect
    self.loop.run_until_complete(self.pipeReader.read())
  File "C:\Python310\lib\asyncio\base_events.py", line 622, in run_until_complete
    self._check_running()
  File "C:\Python310\lib\asyncio\base_events.py", line 582, in _check_running
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
[20-03-2023 09:14:18 AM] [ERROR] An unexpected error occured during a RPC read operation
Traceback (most recent call last):
  File "C:\tools\discord-rich-presence-plex\services\DiscordRpcService.py", line 47, in read
    data = json.loads(dataBytes[8:].decode("utf-8"))
  File "C:\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
C:\tools\discord-rich-presence-plex\services\DiscordRpcService.py:75: RuntimeWarning: coroutine 'StreamReader.read' was never awaited
  logger.exception("An unexpected error occured while closing an IPC pipe reader")
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

**Comment by N72826** [comment]
ok all I did was uninstall and reinstall requirements and it seems the problem resolved itself. If it happens again, I will reopen but everything seems good now.
