### ISSUE TITLE
support for linux/arm/v7 arch

### ISSUE THREAD

**Issue by SensehacK** [phin05/discord-rich-presence-plex#70]
I tried to pull this image on raspberryPi portainer - docker compose option and hit this error

```error
failed to deploy a stack: discord-rich-presence-plex Pulling no matching manifest for linux/arm/v7 in the manifest list entries
```

Config

```yaml


version: '3.3'
services:
    discord-rich-presence-plex:
        # environment:
            # - PLEX_SERVER_NAME=fsociety
        volumes:
            - ./data:/app/data
            - /run/user/1000:/run/app:ro
        restart: unless-stopped
        image: ghcr.io/phin05/discord-rich-presence-plex:latest
        container_name: discord-rich-presence-plex

```

**Comment by phin05** [comment]
Added in v2.4.0.

**Comment by SensehacK** [comment]
It definitely works now but discord client named `WebChord` 
https://raspberrytips.com/install-discord-on-raspberry-pi/ Doesn't connect with the script RPC.

```logs
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 509, in _sock_connect

    sock.connect(address)

PermissionError: [Errno 13] Permission denied

[08-11-2023 07:34:06 PM] [ERROR] An unexpected error occured while connecting to Discord IPC pipe /run/app/discord-ipc-9

Traceback (most recent call last):

  File "/app/core/discord.py", line 29, in handshake

    self.pipeReader, self.pipeWriter = await asyncio.open_unix_connection(ipcPipe) # pyright: ignore[reportGeneralTypeIssues,reportUnknownMemberType]

  File "/usr/local/lib/python3.10/asyncio/streams.py", line 98, in open_unix_connection

    transport, _ = await loop.create_unix_connection(

  File "/usr/local/lib/python3.10/asyncio/unix_events.py", line 255, in create_unix_connection

    await self.sock_connect(sock, path)

  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 501, in sock_connect

    return await fut

  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 509, in _sock_connect

    sock.connect(address)

PermissionError: [Errno 13] Permission denied

[08-11-2023 07:34:06 PM] [ERROR] Discord IPC pipe not found (attempted pipes: /run/app/discord-ipc-0, /run/app/discord-ipc-1, /run/app/discord-ipc-2, /run/app/discord-ipc-3, /run/app/discord-ipc-4, /run/app/discord-ipc-5, /run/app/discord-ipc-6, /run/app/discord-ipc-7, /run/app/discord-ipc-8, /run/app/discord-ipc-9)
```

**Comment by phin05** [comment]
The client you're using doesn't support it.
https://github.com/SpacingBat3/WebCord/issues/292

Maybe you can try https://github.com/ArmCord/ArmCord instead, but keep [this](https://github.com/ArmCord/ArmCord#will-i-get-banned-for-using-this) in mind.

**Comment by SensehacK** [comment]
Hi, 
Tried with `ArmCord` it doesn't support IPC as well.
Thank you for providing this info about various options.



Similar logs

```logs
PermissionError: [Errno 13] Permission denied

[08-11-2023 07:36:17 PM] [ERROR] An unexpected error occured while connecting to Discord IPC pipe /run/app/discord-ipc-9

Traceback (most recent call last):

  File "/app/core/discord.py", line 29, in handshake

    self.pipeReader, self.pipeWriter = await asyncio.open_unix_connection(ipcPipe) # pyright: ignore[reportGeneralTypeIssues,reportUnknownMemberType]

  File "/usr/local/lib/python3.10/asyncio/streams.py", line 98, in open_unix_connection

    transport, _ = await loop.create_unix_connection(

  File "/usr/local/lib/python3.10/asyncio/unix_events.py", line 255, in create_unix_connection

    await self.sock_connect(sock, path)

  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 501, in sock_connect

    return await fut

  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 509, in _sock_connect

    sock.connect(address)

PermissionError: [Errno 13] Permission denied

[08-11-2023 07:36:17 PM] [ERROR] Discord IPC pipe not found (attempted pipes: /run/app/discord-ipc-0, /run/app/discord-ipc-1, /run/app/discord-ipc-2, /run/app/discord-ipc-3, /run/app/discord-ipc-4, /run/app/discord-ipc-5, /run/app/discord-ipc-6, /run/app/discord-ipc-7, /run/app/discord-ipc-8, /run/app/discord-ipc-9)
```

**Comment by phin05** [comment]
ArmCord's README says that it supports IPC. Are you sure `/run/user/1000` is the correct directory? Is that what your `XDG_RUNTIME_DIR` environment variable is set to? Is there a `discord-ipc-X` file inside that while ArmCord is running?

**Comment by SensehacK** [comment]
I even turned on https://github.com/OpenAsar/arrpc#server-required for ArmChord but still same error for IPC.

So my local directory has `/run/user/1000` has `discord-ipx-0` socket file.


But I don't think so I have set the four environment variables required.
I'm adding that 
```yaml
version: '3.3'
services:
    discord-rich-presence-plex:
        environment:
           ## Adding this environment variable now.
            - XDG_RUNTIME_DIR=/run/user/1000 
            - PLEX_SERVER_NAME=redacted_server_name
        volumes:
            - ./data:/app/data
            - /run/user/1000:/run/app:ro
        # restart: unless-stopped
        image: ghcr.io/phin05/discord-rich-presence-plex:latest
        container_name: discord-rich-presence-plex
```


Also I do have `/tmp` directory which `dhcpcd-pi` which has 2 files `libdhcpcd-wpa-2207.0 & .1`

**Comment by SensehacK** [comment]
In the portainer logs it tries to run at `/run/app/discord-ipc-` but shouldn't it run `run/user/1000/discord-ipc-0` ? 
I'm pretty new to docker and unix mounting - sockets stuff. Happy to learn and debug with you to provide more context.


```log
Traceback (most recent call last):

  File "/app/core/discord.py", line 29, in handshake

    self.pipeReader, self.pipeWriter = await asyncio.open_unix_connection(ipcPipe) # pyright: ignore[reportGeneralTypeIssues,reportUnknownMemberType]

  File "/usr/local/lib/python3.10/asyncio/streams.py", line 98, in open_unix_connection

    transport, _ = await loop.create_unix_connection(

  File "/usr/local/lib/python3.10/asyncio/unix_events.py", line 255, in create_unix_connection

    await self.sock_connect(sock, path)

  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 501, in sock_connect

    return await fut

  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 509, in _sock_connect

    sock.connect(address)

PermissionError: [Errno 13] Permission denied

[16-11-2023 05:16:30 PM] [ERROR] Discord IPC pipe not found (attempted pipes: /run/app/discord-ipc-0, /run/app/discord-ipc-1, /run/app/discord-ipc-2, /run/app/discord-ipc-3, /run/app/discord-ipc-4, /run/app/discord-ipc-5, /run/app/discord-ipc-6, /run/app/discord-ipc-7, /run/app/discord-ipc-8, /run/app/discord-ipc-9)
```

**Comment by phin05** [comment]
You don't need to set the `XDG_RUNTIME_DIR` environment variable for the container. I was asking how you decided on `/run/user/1000`. Is that what `XDG_RUNTIME_DIR` is set to on the host machine?

What's the output of the following commands on the host machine? (while both ArmCord and the Docker container are running)
```
echo $XDG_RUNTIME_DIR, $TMPDIR, $TMP, $TMPDIR
sudo find / -name discord-ipc-*
docker exec discord-rich-presence-plex ls -l /run/app/discord-ipc-0
```

> In the portainer logs it tries to run at /run/app/discord-ipc- but shouldn't it run run/user/1000/discord-ipc-0

`/run/app` is correct. That's the path inside the container where the host folder containing Discord's IPC Unix socket file should be mounted.

**Comment by SensehacK** [comment]
```sh
echo $XDG_RUNTIME_DIR, $TMPDIR, $TMP, $TEMP
/run/user/1001, , ,
```



```sh
sudo find / -name discord-ipc-*
[sudo] password for kautilya:
/run/user/1000/discord-ipc-0
find: ‘/run/user/1000/gvfs’: Permission denied
```



```sh
docker exec drpp ls -l /run/app/discord-ipc-0
srwxr-xr-x    1 1000     1000             0 Nov 15 22:47 /run/app/discord-ipc-0

```

previously it was /run/user/1000 ( when using Portainer ) to run now I used the normal docker command and now it has 
`/run/user/1001`
`/run/user` directory has two folders.

**Comment by phin05** [comment]
I'm not sure what's going on there. Are you using multiple users? Is ArmCord running in the same environment as the one you're running these commands on?

If `XDG_RUNTIME_DIR` is set to `/run/user/1001` in ArmCord's environment, that's the folder where it should be storing the Unix socket file, and that's the folder you need to mount into the container as `/run/app` (`/run/user/1001:/run/app:ro`).

> previously it was /run/user/1000 ( when using Portainer ) to run now I used the normal docker command and now it has
/run/user/1001

I don't see how that's possible. Docker doesn't affect this.
